version: "3.8"

services:
  main:
    container_name: main
    build:
      context: .
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:6.0.8-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/var/lib/redis
      - redis_conf:/etc/redis/redis.conf
  postgres:
    container_name: postgres
    image: postgres:12.4
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
  redis_data:
  redis_conf: